# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Personal blog
sub-title: maximilian.tech
email:       ''
description: ''
baseurl:     '' # The subpath of your site, e.g. /blog
url:         'https://maximilian.tech' # The base hostname & protocol for your site
twitter:     ''
github:      'https://github.com/m1nka/'
instagram:   ''
facebook:    ''

markdown:  kramdown
permalink: pretty
paginate:  10

sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll/tagging
  - jekyll-sitemap

include:
  - _pages

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - CNAME
  - LICENSE
  - README.md
  - deploy

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

# Pages path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext