name: deploy-blog

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: 🛎 Check out master
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: 🧪 Build and deploy
        uses: victoriadrake/jekyll-cd@bb775fd060be80d8f295d9214c7f98f871413809
      - name: copy files via ssh key
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          source: "docs/*"
          target: "/home/opc/temp/"
      - name: executing remote ssh commands using key
        uses: appleboy/ssh-action@8a92fcdb1eb4ffbf538b2fa286739760aac8a95b
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            sudo rm -rf /var/www/html/*
            sudo mv /home/opc/temp/docs/* /var/www/html/
