name: jekyll-cd

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: 🛎 Check out master
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: 🧪 Build and deploy
        uses: victoriadrake/jekyll-cd@698f19e
      - name: copy files via ssh key
        uses: appleboy/scp-action@edc8ec9        
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          source: "docs/*"
          target: "/home/opc/temp/"
      - name: executing remote ssh commands using key
        uses: appleboy/ssh-action@fd39ef0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            sudo rm -rf /var/www/html/*
            sudo mv /home/opc/temp/docs/* /var/www/html/